### ISSUE TITLE
Results are not the same as the ones in paper

### ISSUE THREAD

**Issue by sea2603** [Zhilin123/personal_attributes#1]
Hi @Zhilin123 ,
It's a good job. But the results are not the same as those mentioned in the [paper](https://arxiv.org/abs/2109.12702). I run the code using the default parameters. F1 reached 52.38% in extraction dataset and **1.21%** in inference dataset. After setting inference task **LR=7.5e-4** (the same as extraction task) in generator_model.py, F1 reached **11.5%**. It's still far from the results of the paper.

**Comment by Zhilin123** [comment]
Thanks for raising this! It will be great if you can specify the exact script you ran. Among other possible differences from the paper, I noticed that you used LR=7.5e-4 for the inference task while the paper specified LR=2.5*10-3 for this task (see Appendix A.4).

**Comment by sea2603** [comment]
I use the same parameters as in [train.sh](https://github.com/Zhilin123/personal_attributes/blob/main/train.sh)
I first train on extraction dataset, then on inference dataset.
training log as below.
[extraction_reranker.txt]
In line 539604 of training log, f1 still equals 0.0121 after 8 epochs' training of reranker model.
Is it convenient for you to post training log of the best model?
Thanks for your time.

**Comment by Zhilin123** [comment]
Hi, if you're interested in the inference dataset, you should train on only the inference dataset, as we show in train.sh. It would not be convenient to post our training logs, unfortunately.

**Comment by sea2603** [comment]
Thanks anyway.

**Comment by Zhilin123** [comment]
You're welcome! Will close this issue, feel free to raise others when they arise.
